Net-CPP: IP Class Reference
IP Class Reference
Used to represent an IP address.
#include <IP.hpp>
Public Member Functions
IP (const std::string &addr, const std::string &mask)
std::string get () const
const std::string & get_address () const
const std::string & get_mask () const
bool operator== (const IP &other) const
std::string to_string () const
Private Attributes
std::string address_
IP Address.
std::string mask_
Subnet mask.
Detailed Description
Used to represent an IP address.
This class is used to represent an IP address using the address itself and its subnet mask
Examples
src/examples/ip_usage.cpp.
Definition at line 15 of file IP.hpp.
Constructor & Destructor Documentation
IP()
IP::IP (const std::string & addr, const std::string & mask)
Member Function Documentation
get()
std::string IP::get () const
Examples
src/examples/ip_usage.cpp.
Referenced by main().
get_address()
const std::string & IP::get_address () const
Examples
src/examples/ip_usage.cpp.
Referenced by main().
get_mask()
const std::string & IP::get_mask () const
Examples
src/examples/ip_usage.cpp.
Referenced by main().
operator==()
bool IP::operator== (const IP & other) const
to_string()
std::string IP::to_string () const
Examples
src/examples/ip_usage.cpp.
Referenced by main().
Member Data Documentation
address_
std::string IP::address_ private
IP Address.
Definition at line 19 of file IP.hpp.
mask_
std::string IP::mask_ private
Subnet mask.
Definition at line 21 of file IP.hpp.
The documentation for this class was generated from the following file:
src/include/IP.hpp