Net-CPP: src/examples/ip_usage.cpp File Reference
ip_usage.cpp File Reference
#include "../include/IP.hpp"
#include <iostream>
Functions
int main ()
Function Documentation
main()
int main ()
Examples
src/examples/ip_usage.cpp.
Definition at line 4 of file ip_usage.cpp.
{
  // Create an IP object
  IP ip("127.0.0.1", "32");
  // get() method showcase
  std::cout << ip.get() << "\n"; // -> "127.0.0.1/32"
  // get_address() method showcase
  std::cout << ip.get_address() << "\n"; // -> "127.0.0.1"
  // get_mask() method showcase
  std::cout << ip.get_mask() << "\n"; // -> "32"
  // operator== overloading showcase
  IP other_ip("192.168.0.1", "32");
  std::cout << ((ip == other_ip) ? "true" : "false") << "\n"; // -> false
  // to_string() method showcase
  std::string result = ip.to_string(); // -> IP(address_ : "127.0.0.1", mask_ : "32")
  // operator<< overloading showcase
  std::cout << ip << "\n";
  return 0;
}
References IP::get(), IP::get_address(), IP::get_mask(), and IP::to_string().